"""TTS generation with multi-speaker support, segment caching, silence trimming, and timeline sync."""

from __future__ import annotations

import asyncio
import json
import os
import shutil
import subprocess
import time
from pathlib import Path

import edge_tts
from pydub import AudioSegment
from pydub.silence import detect_leading_silence

from config import LANGUAGES, OUTPUT_FOLDER, SPEAKER_VOICE_MAPS, TTS_VOICES, UPLOAD_FOLDER, jobs
from services.google_tts import synthesize_to_wav
from services.srt_utils import parse_srt_timing

BASE_DIR = Path(__file__).resolve().parent.parent
OMNIVOICE_PYTHON = Path(os.getenv("OMNIVOICE_PYTHON", r"D:\Naldo\omnivoice-env\Scripts\python.exe"))
OMNIVOICE_WORKER = BASE_DIR / "services" / "omnivoice_worker.py"
DEFAULT_CLONE_AUDIO = Path(os.getenv("OMNIVOICE_REFERENCE_AUDIO", ""))
DEFAULT_CLONE_TEXT = ""
if os.getenv("OMNIVOICE_REFERENCE_TEXT_FILE"):
    try:
        DEFAULT_CLONE_TEXT = Path(os.environ["OMNIVOICE_REFERENCE_TEXT_FILE"]).read_text(encoding="utf-8").strip()
    except OSError:
        DEFAULT_CLONE_TEXT = ""


def _cancelled(job_id: str) -> bool:
    return bool(jobs.get(job_id, {}).get("cancel"))


def _mark_progress(job_id: str, key: str, progress: int, message: str) -> None:
    jobs[job_id].setdefault(key, {})["progress"] = progress
    jobs[job_id][key]["message"] = message


def _trim_silence(audio: AudioSegment, silence_threshold: int = -40, padding_ms: int = 40) -> AudioSegment:
    """Trim leading and trailing silence padding generated by TTS engines."""
    orig_len = len(audio)
    if orig_len <= 100:
        return audio
    start_trim = detect_leading_silence(audio, silence_threshold=silence_threshold)
    end_trim = detect_leading_silence(audio.reverse(), silence_threshold=silence_threshold)
    start_pos = max(0, start_trim - padding_ms)
    end_pos = min(orig_len, orig_len - end_trim + padding_ms)
    if start_pos < end_pos:
        return audio[start_pos:end_pos]
    return audio


def _speed_audio_to_fit(source_path: str, audio: AudioSegment, max_duration_ms: int) -> AudioSegment:
    """Trim silence and adjust speed gently to fit the subtitle slot without distortion."""
    audio = _trim_silence(audio)
    curr_len = len(audio)
    if max_duration_ms <= 0 or curr_len <= max_duration_ms:
        return audio

    speed_ratio = curr_len / max_duration_ms
    if speed_ratio <= 1.15:
        return audio

    clamped_ratio = min(speed_ratio, 1.8)
    filters = []
    remaining = clamped_ratio
    while remaining > 1.0:
        factor = min(remaining, 2.0)
        filters.append(f"atempo={factor:.4f}")
        remaining /= factor

    temp_trim = str(Path(source_path).with_suffix(".trim.wav"))
    audio.export(temp_trim, format="wav")
    sped_path = str(Path(source_path).with_suffix(".sped.wav"))

    result = subprocess.run(
        ["ffmpeg", "-y", "-i", temp_trim, "-filter:a", ",".join(filters), "-vn", sped_path],
        capture_output=True,
        timeout=15,
    )
    Path(temp_trim).unlink(missing_ok=True)
    if result.returncode == 0 and os.path.exists(sped_path):
        try:
            return AudioSegment.from_wav(sped_path)
        finally:
            Path(sped_path).unlink(missing_ok=True)
    return audio


def _resolve_speaker_voice(engine: str, lang: str, speaker_id: str, custom_map: dict | None = None) -> tuple[str, str]:
    """Resolve the voice name and pitch/emotion for a given speaker."""
    if custom_map and speaker_id in custom_map:
        val = custom_map[speaker_id]
        if isinstance(val, str):
            return val, "+0Hz" if engine == "edge" else "warm"
        if isinstance(val, dict):
            return val.get("voice", TTS_VOICES.get(lang, "vi-VN-NamMinhNeural")), val.get("pitch", "+0Hz")

    engine_map = SPEAKER_VOICE_MAPS.get(engine, {}).get(lang, {})
    if speaker_id in engine_map:
        info = engine_map[speaker_id]
        return info["voice"], info.get("pitch", "+0Hz") if engine == "edge" else info.get("emotion", "warm")

    default_v = TTS_VOICES.get(lang, "vi-VN-NamMinhNeural")
    return default_v, "+0Hz" if engine == "edge" else "warm"


def generate_edge_tts_audio(
    job_id: str,
    lang: str,
    segments: list,
    total: int,
    temp_dir: Path,
    tts_key: str,
    speaker_voices: dict | None = None,
):
    segment_speakers = jobs.get(job_id, {}).get("segment_speakers") or ["M1"] * len(segments)

    async def generate_single_segment(index: int, text: str):
        spk = segment_speakers[index] if index < len(segment_speakers) else "M1"
        voice, pitch = _resolve_speaker_voice("edge", lang, spk, speaker_voices)
        output = temp_dir / f"seg_{index:04d}_{spk}.mp3"
        if output.exists() and output.stat().st_size > 0:
            return str(output)

        last_error = None
        for attempt in range(5):
            if _cancelled(job_id):
                raise RuntimeError("Đã hủy TTS (Stop)")
            try:
                communicate = edge_tts.Communicate(text, voice, pitch=pitch)
                await communicate.save(str(output))
                if output.exists() and output.stat().st_size > 0:
                    return str(output)
            except Exception as exc:
                last_error = exc
                if attempt < 4:
                    await asyncio.sleep(2 + attempt * 2)
        print(f"Edge-TTS segment {index} ({spk}) failed: {last_error}")
        return None

    async def generate_all():
        paths = [None] * len(segments)
        missing_indices = []

        for i in range(len(segments)):
            spk = segment_speakers[i] if i < len(segment_speakers) else "M1"
            p = temp_dir / f"seg_{i:04d}_{spk}.mp3"
            if p.exists() and p.stat().st_size > 0:
                paths[i] = str(p)
            else:
                missing_indices.append(i)

        if not missing_indices:
            return paths

        batch_size = 2 if len(missing_indices) <= 6 else 3
        done_count = len(segments) - len(missing_indices)
        for start_idx in range(0, len(missing_indices), batch_size):
            if _cancelled(job_id):
                raise RuntimeError("Đã hủy TTS (Stop)")
            batch_ids = missing_indices[start_idx : start_idx + batch_size]
            results = await asyncio.gather(*[
                generate_single_segment(idx, segments[idx][2]) for idx in batch_ids
            ])
            for idx, path in zip(batch_ids, results):
                paths[idx] = path
            done_count += len(batch_ids)
            _mark_progress(job_id, tts_key, int(done_count / total * 80), f"Đang tạo audio: {done_count}/{total}")
            await asyncio.sleep(0.5)

        return paths

    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(generate_all())
    finally:
        loop.close()


def generate_omnivoice_audio(job_id: str, lang: str, segments: list, total: int, temp_dir: Path, tts_key: str):
    if not OMNIVOICE_PYTHON.exists():
        raise RuntimeError(f"Không tìm thấy OmniVoice Python: {OMNIVOICE_PYTHON}")
    if not OMNIVOICE_WORKER.exists():
        raise RuntimeError("Không tìm thấy OmniVoice worker")
    if not DEFAULT_CLONE_AUDIO or not DEFAULT_CLONE_AUDIO.exists():
        raise RuntimeError("Chưa cấu hình file reference audio cho OmniVoice")

    input_path = temp_dir / "omnivoice_input.json"
    input_path.write_text(json.dumps({
        "segments": [segment[2] for segment in segments],
        "lang": lang,
        "ref_audio": str(DEFAULT_CLONE_AUDIO),
        "ref_text": DEFAULT_CLONE_TEXT,
        "speed": 1.1,
        "out_dir": str(temp_dir),
    }, ensure_ascii=False), encoding="utf-8")

    process = subprocess.Popen(
        [str(OMNIVOICE_PYTHON), str(OMNIVOICE_WORKER), str(input_path)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.STDOUT,
        text=True,
    )
    jobs[job_id]["_tts_process"] = process
    try:
        while process.poll() is None:
            if _cancelled(job_id):
                process.terminate()
                raise RuntimeError("Đã hủy TTS (Stop)")
            generated = len(list(temp_dir.glob("seg_*.wav")))
            _mark_progress(job_id, tts_key, int(generated / total * 80), f"Đang clone giọng AI: {generated}/{total}")
            time.sleep(2)
        result_path = temp_dir / "result.json"
        if process.returncode != 0 or not result_path.exists():
            raise RuntimeError("OmniVoice worker thất bại hoặc crash")
        result = json.loads(result_path.read_text(encoding="utf-8"))
        if result.get("status") != "success":
            raise RuntimeError(f"OmniVoice: {result.get('message', 'unknown error')}")
        return [str(path) if path.exists() else None for path in [temp_dir / f"seg_{i:04d}.wav" for i in range(total)]]
    finally:
        jobs.get(job_id, {}).pop("_tts_process", None)


def generate_gemini_tts_audio(
    job_id: str,
    lang: str,
    segments: list,
    total: int,
    temp_dir: Path,
    tts_key: str,
    options: dict | None = None,
    speaker_voices: dict | None = None,
):
    options = options or {}
    style_prompt = str(options.get("style_prompt") or "").strip()[:500]
    segment_speakers = jobs.get(job_id, {}).get("segment_speakers") or ["M1"] * len(segments)

    paths = []
    for index, (_start, _end, text) in enumerate(segments):
        if _cancelled(job_id):
            raise RuntimeError("Đã hủy TTS (Stop)")
        spk = segment_speakers[index] if index < len(segment_speakers) else "M1"
        voice, emotion = _resolve_speaker_voice("gemini", lang, spk, speaker_voices)
        output = temp_dir / f"seg_{index:04d}_{spk}.wav"
        if output.exists() and output.stat().st_size > 0:
            paths.append(str(output))
            continue
        try:
            synthesize_to_wav(
                text, output, lang=lang, voice=voice, emotion=emotion,
                style_prompt=style_prompt, continuation=index > 0,
                cancelled=lambda: _cancelled(job_id),
            )
            paths.append(str(output))
        except Exception as exc:
            print(f"Gemini TTS segment {index} ({spk}) failed: {exc}")
            paths.append(None)
        _mark_progress(job_id, tts_key, int((index + 1) / total * 80), f"Gemini đang tạo giọng: {index + 1}/{total}")
    return paths


def generate_tts_audio(
    job_id: str,
    lang: str,
    srt_content: str,
    engine: str = "edge",
    options: dict | None = None,
    speaker_voices: dict | None = None,
):
    segments = parse_srt_timing(srt_content)
    if not segments:
        raise RuntimeError("Không tìm thấy phụ đề để tạo audio")
    if lang not in LANGUAGES:
        raise ValueError(f"Ngôn ngữ không được hỗ trợ: {lang}")

    tts_key = f"tts_{lang}"
    jobs[job_id][tts_key] = {"status": "generating", "progress": 0, "message": f"Đang khởi tạo TTS ({engine})..."}
    temp_dir = UPLOAD_FOLDER / job_id / f"tts_{lang}"
    temp_dir.mkdir(parents=True, exist_ok=True)
    try:
        if engine == "omnivoice":
            segment_paths = generate_omnivoice_audio(job_id, lang, segments, len(segments), temp_dir, tts_key)
        elif engine == "gemini":
            segment_paths = generate_gemini_tts_audio(job_id, lang, segments, len(segments), temp_dir, tts_key, options, speaker_voices)
        else:
            segment_paths = generate_edge_tts_audio(job_id, lang, segments, len(segments), temp_dir, tts_key, speaker_voices)

        _mark_progress(job_id, tts_key, 85, "Đang ghép audio theo timeline...")
        video_duration_ms = int(float(jobs[job_id].get("duration", 0) or 0) * 1000)
        total_duration_ms = max(video_duration_ms, segments[-1][1] + 2000)
        final_audio = AudioSegment.silent(duration=total_duration_ms)
        failures = []
        for index, (start_ms, end_ms, _text) in enumerate(segments):
            source = segment_paths[index] if index < len(segment_paths) else None
            if not source or not os.path.exists(source):
                failures.append(index)
                continue
            try:
                audio = AudioSegment.from_wav(source) if source.endswith(".wav") else AudioSegment.from_mp3(source)
                next_start = segments[index + 1][0] if index + 1 < len(segments) else end_ms + 2000
                audio = _speed_audio_to_fit(source, audio, max(1, next_start - start_ms))
                final_audio = final_audio.overlay(audio, position=start_ms)
            except Exception as exc:
                failures.append(index)
                print(f"TTS overlay segment {index} failed: {exc}")

        _mark_progress(job_id, tts_key, 95, "Đang export MP3...")
        output_dir = OUTPUT_FOLDER / job_id
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"tts_{lang}.mp3"
        final_audio.export(str(output_path), format="mp3", bitrate="192k")
        size = output_path.stat().st_size
        status = "partial" if failures else "done"
        jobs[job_id][tts_key] = {
            "status": status,
            "progress": 100,
            "message": f"Hoàn thành ({size / 1048576:.1f}MB)" + (f" • thiếu {len(failures)} đoạn" if failures else ""),
            "path": str(output_path),
            "filename": f"tts_{LANGUAGES[lang]['name']}_{job_id}.mp3",
            "size": size,
            "duration": round(len(final_audio) / 1000, 1),
            "failed_segments": failures,
            "total_segments": len(segments),
        }
    except Exception as exc:
        jobs[job_id][tts_key] = {"status": "error", "progress": 0, "message": f"Lỗi TTS: {exc}"}
        raise


def tts_worker(
    job_id: str,
    lang: str,
    srt_content: str,
    engine: str = "edge",
    options: dict | None = None,
    speaker_voices: dict | None = None,
):
    try:
        generate_tts_audio(job_id, lang, srt_content, engine, options, speaker_voices)
    except Exception as exc:
        print(f"TTS Worker exception: {exc}")
